# Generated by Django 6.0.8 on 2026-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosVehiculo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('factor_depreciacion', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'ESTADOS_VEHICULO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'MARCAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('anio_inicio', models.IntegerField()),
                ('tipo_carroceria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'MODELOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreciosVehiculos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_precio', models.CharField(max_length=20)),
                ('fuente', models.CharField(max_length=20)),
                ('fecha_precio', models.DateTimeField()),
            ],
            options={
                'db_table': 'PRECIOS_VEHICULOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('anio_vehiculo', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'VEHICULOS',
                'managed': False,
            },
        ),
    ]
